### PR TITLE
shownotes added to the rss feed + small feed cleaning

### PR DESCRIPTION
**Pull request by siejkowski**

### CODE REVIEW

**Comment by notthetup** [comment]
DOH! We both changed at the same time!! Could I ask you to rebase??

**Comment by siejkowski** [comment]
rebased and squashed. 

i had to put CDATA around description as well if it's where the tag-contaning content is gonna be kept. it's not by the book, i know: http://stackoverflow.com/questions/7220670/difference-between-description-and-contentencoded-tags-in-rss2

on the bright side, this is exactly what the overcast author is doing himself :P http://atp.fm/episodes?format=rss

**Comment by siejkowski** [comment]
Actually, maybe it's better to leave the `<description>` tag unchanged? Not sure whether `<content:encoded>` is parsed properly by the podcast apps. Btw I wish there's something like [putsmail.com](putsmail.com) for podcast feeds.

**Comment by siejkowski** [comment]
Ok, overcast is happy on content:encoded alone, and I'm happy too :) Gonna close pr, thanks for the shownotes!

**Comment by notthetup** [comment]
:+1:

**Comment by sayanee** [comment]
cooool... installing overcast :+1: thanks @siejkowski

**Pull request closed without merging**
